Homework/Homework/urls.py
"""Homework URL Configuration
"""

from django.conf.urls import url, include
from django.contrib import admin
# from allauth.account import views as allauthviews


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('homework.urls',namespace="homework")),
]

Homework/homework/urls.py
from django.conf.urls import url
from homework import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
]

Homework/homework/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True

class City(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Cities"

class Customer(BaseModel):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.BigIntegerField(
                        validators=[
                            MaxValueValidator(10),
                            MinValueValidator(10)
                        ]
                     )
    # Currently, I have only provided support for mobile number, for future enhancement, we can update it so that it can accept, landline and country code etc.
      
    def __str__(self):
        return self.first_name + " " + self.last_name

class Cleaner(BaseModel):
    """docstring for Cleaner"""
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    quality_score = models.DecimalField(max_digits=10, decimal_places=2)
  
    def __str__(self):
        return self.first_name + " " + self.last_name

class CleanerCityMap(BaseModel):
    Cleaner = models.ForeignKey(Cleaner)
    City = models.ForeignKey(City)

    class Meta:
        unique_together = ('Cleaner', 'City')

    def __str__(self):
        return "{}_{} - {}".format(self.Cleaner.first_name, self.Cleaner.last_name ,self.City.name)
    

class Booking(BaseModel):
    Customer = models.ForeignKey(Customer)
    Cleaner = models.ForeignKey(Cleaner)
    date =  models.DateTimeField()

    def __str__(self):
        return "{} {} -{} {} -{}".format(self.Customer.first_name, self.Customer.last_name ,self.Cleaner.first_name, self.Cleaner.last_name, self.date.strftime("%m-%d-%Y %H:%M"))
    

Homework/homework/forms.py
from django import forms
import datetime
from .models import City

class HomeWorkForm(forms.Form):
    first_name = forms.CharField(max_length=20,required=True)
    last_name = forms.CharField(max_length=20,required=True)
    phone_number = forms.IntegerField(required=True)
    city = forms.ModelChoiceField(queryset=City.objects.all().order_by('name'), required=True,label='Select city')
    date= forms.DateTimeField(input_formats=["%m-%d-%Y %H:%M"])

Homework/homework/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from .models import *
from .forms import HomeWorkForm

def index(request):
    context = {}
    context['form'] = HomeWorkForm()
    if request.method == "POST":
        input_form = HomeWorkForm(request.POST)
        if input_form.is_valid():
            first_name = input_form.cleaned_data.get('first_name', None)
            last_name = input_form.cleaned_data.get('last_name', None)
            phone_number = input_form.cleaned_data.get('phone_number', None)
            city = input_form.cleaned_data.get('city', None)
            date = input_form.cleaned_data.get('date', None)
            
            customer = None
            try:
                customer = Customer.objects.get(phone_number=phone_number)
                # If customer first_name and last_name is different, then I am not doing anything at this time.
            except Exception as e:
                # Check for the new customer and sign in them into the system.
                customer = Customer(first_name = first_name, last_name = last_name, phone_number = phone_number)
                customer.save()
            
            cleaners = CleanerCityMap.objects.filter(City__name = city).values_list('Cleaner', flat=True)
            if not cleaners:
                context["info_message"] = "Cleaner is not available at your city"
            else:
                booked_cleaners = Booking.objects.filter(Cleaner__in = cleaners, date = date).values_list('Cleaner', flat=True)            
                available_cleaners = Cleaner.objects.filter(id__in=cleaners).exclude(id__in=booked_cleaners)
                if available_cleaners:
                    booking = Booking(Customer=customer, Cleaner=available_cleaners.first(), date=date)
                    booking.save()
                    context["success_message"] = "Booking is created successfully"
                else:
                    context["info_message"] = "Cleaner is not available at provided date time"
            # We can use Django messages in here
            form = HomeWorkForm()
        else:
            context['form'] = HomeWorkForm()
    return render(request, 'homework/index.html', context)

Homework/homework/templates/homework/base.html
<!-- In the base.html we can define all of our assets like css and js file and also create header and footer which is used by the whole application. -->
<body>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <div class="page-header">
        <h1>HomeWork</h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>

Homework/homework/templates/homework/index.html
{% extends "homework/base.html" %}


{% block content %}
	{% if success_message %}
		<div class="alert alert-success">
		  	{{ success_message }}
		</div>
	{% endif%}

	{% if info_message %}
		<div class="alert alert-info">
		  	{{ info_message }}
		</div>
	{% endif%}

	<form id="homework_form" name="homework_form" method="POST", action="{% url 'homework:index' %}">
	{% csrf_token %}
		{{ form.non_field_errors }}
		<div class="fieldWrapper">
		    {% if form.first_name.errors %}
			    <div class="alert alert-danger">
				  	 {{ form.first_name.errors }}
				</div>
			{% endif %}
		    <label for="{{ form.first_name.id_for_label }}">First Name: </label>
		    {{ form.first_name }}
		</div>

		<div class="fieldWrapper">
		    {% if form.last_name.errors %}
			    <div class="alert alert-danger">
				  	 {{ form.last_name.errors }}
				</div>
			{% endif %}
		    <label for="{{ form.last_name.id_for_label }}">Last Name: </label>
		    {{ form.last_name }}
		</div>

		<div class="fieldWrapper">
		    {% if form.phone_number.errors %}
			    <div class="alert alert-danger">
				  	 {{ form.phone_number.errors }}
				</div>
			{% endif %}
		    <label for="{{ form.phone_number.id_for_label }}">Phone Number: </label>
		    {{ form.phone_number }}
		</div>

		<div class="fieldWrapper">
		    {% if form.city.errors %}
			    <div class="alert alert-danger">
				  	 {{ form.city.errors }}
				</div>
			{% endif %}
		    <label for="{{ form.city.id_for_label }}">Select City :</label>
		    {{ form.city }}
		</div>

		<div class="fieldWrapper">
		    {% if form.date.errors %}
			    <div class="alert alert-danger">
				  	 {{ form.date.errors }}
				</div>
			{% endif %}
		    <label for="{{ form.date.id_for_label }}">Date :</label>
		    {{ form.date }}
		</div>

		<button type="submit"> Submit </button>
	</form>

<script type="text/javascript">
    $(function () {
        $('#id_date').datetimepicker(
        	{'sideBySide': true, "showClose": true,  "format": 'MM-DD-YYYY HH:mm', "minDate":new Date()});
    });

    $( "#homework_form" ).submit(function( event ) {
    	phone_number = $("#id_phone_number").val()
    	if (phone_number.length != 10){
		  event.preventDefault();
		  alert("Please enter a valid 10 digit mobile number")
    	}
	});


</script>
{% endblock %}